apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-5g
spec:
  capacity:
    storage: 5Gi  # 逻辑容量5GB
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/k8s-pv-01  # 指向/home下的专用目录
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node1  # 你的节点名，直接填好可用
  volumeMode: Filesystem
