apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-5g
  namespace: ai-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeMode: Filesystem
