apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    app: my-app
    storage: local-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /data/k8s/local-storage  # 确认该路径已存在且权限777
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node1  # 正确节点名（无短横线）
  persistentVolumeReclaimPolicy: Delete
